# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6dadd18ad3eee5176b51649918fcc3bf60ec0e68305444d5623d8f731e03e0ea28708106a2415e767599f3cc26f867a29988f86cb941ac1d4e4d940bcb5d869f

test:
  secret_key_base: d02cd4df65a73ff08e5659c7b65a5fc18b377e4eb65344084ef99afe2019ad93016152ab18199d556501ab76901de0fad1fdf629f8556763add8b644f8e16ea9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
